name: AWS CLI for Github Actions
description: Run AWS CLI commands
author: labac-p
branding:
  icon: cloud
  color: yellow
runs:
  using: docker
  image: docker://public.ecr.aws/aws-cli/aws-cli:2.23.12
